# Generated by Django 6.0.2 on 2026-03-02 17:26

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_alter_student_courses"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": [
                    django.db.models.functions.text.Lower("last_name"),
                    django.db.models.functions.text.Lower("first_name"),
                ]
            },
        ),
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.category"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
